### ISSUE TITLE
Create script to get database dump

### ISSUE THREAD

**Issue by achakravarti** [bstarynk/helpcovid#12]
As was discussed on 31 March, we need a script that creates a dump of the HelpCovid database. This script may either be a Shell script or a Python script, and it needs to read the HelpCovid configuration file generated by the `generate-config.py` script to determine the database connection string. This script will also need to take into account that the path of the HelpCovid configuration file may be different from the default `$HOME/.helpcovidrc`

**Comment by bstarynk** [comment]
In commit bdbabbd3ad226b417c1f3 the `./backup-database.py`  is asking for the PostGreSQL password. There should be a way (documented in `README.md`  and/or with `--help` ...), at least for debugging purposes, to output the SQL dump to *stdout* without having to type any password.

**Comment by bstarynk** [comment]
If the dump file is a gzip-ed SQL file, its name should end with `.sql.gz`

**Comment by achakravarti** [comment]
> In commit [bdbabbd](https://github.com/bstarynk/helpcovid/commit/bdbabbd3ad226b417c1f30ae031ecd232c986438) the `./backup-database.py` is asking for the PostGreSQL password. There should be a way (documented in `README.md` and/or with `--help` ...), at least for debugging purposes, to output the SQL dump to _stdout_ without having to type any password.

The `--dry-run` option has been provided which dumps the SQL to `stdout`

**Comment by achakravarti** [comment]
> If the dump file is a gzip-ed SQL file, its name should end with `.sql.gz`

This has also been incorporated.

**Comment by bstarynk** [comment]
On 4/2/20 9:07 PM, Abhishek Chakravarti wrote:
>
> The |--dry-run| option has been provided which dumps the SQL to |stdout|
>

Then that option name is confusing. Since --dry-run suggests no side 
effects. A bit like the -n option of make.


Please replace --dry-run with --to-stdout and of course have a working 
--help


Thanks

-- 
Basile STARYNKEVITCH   == http://starynkevitch.net/Basile
opinions are mine only - les opinions sont seulement miennes
Bourg La Reine, France; <basile@starynkevitch.net>
(mobile phone: cf my web page / voir ma page web...)

**Comment by bstarynk** [comment]
Thanks. Closed in commit e15d232b25301182f0
